### ISSUE TITLE
Can you share the information about your datasets?

### ISSUE THREAD

**Issue by SeuTao** [KaleidoZhouYN/Details-on-Face-Recognition#9]
You mentioned that your results on LFW is 99.76% of your own dataset.  What's the scale of your data?

**Comment by KaleidoZhouYN** [comment]
about 100K identity with open dataset and Asia people,Augment with eyeglasses and expression.

**Comment by shenmanmiao** [comment]
@KaleidoZhouYN , Could you tell us more details about augmentation with eyeglass and expression? Does it help a lot on performance?

**Comment by SeuTao** [comment]
Thanks a lot. Did u do your augmentation with GAN? I am now trying GAN to augment my own data, but it's hard to preserve the identity information. Not sure it will help.

**Comment by KaleidoZhouYN** [comment]
@shenmanmiao well,you can try starGAN
